# Generated by Django 3.2 on 2021-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpost',
            name='expiry_date',
            field=models.CharField(max_length=100),
        ),
    ]
