# Generated by Django 3.2 on 2021-04-23 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_post_app', '0003_fieldapplication_fieldpostprofession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpost',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
