# Generated by Django 3.2 on 2021-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_post_app', '0004_alter_fieldpost_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldapplication',
            name='application_status',
            field=models.BooleanField(default=False),
        ),
    ]
