# Generated by Django 3.2 on 2021-04-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_post_app', '0006_alter_fieldapplication_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldapplication',
            name='application_status',
        ),
    ]
