# Generated by Django 3.2 on 2021-04-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_post_app', '0007_remove_fieldapplication_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldpost',
            old_name='post_name',
            new_name='post_title',
        ),
    ]
