# Generated by Django 3.2 on 2021-06-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0004_rename_department_id_program_department'),
        ('field_post_app', '0011_alter_fieldpost_post_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldpost',
            old_name='post_descrption',
            new_name='post_description',
        ),
        migrations.AlterField(
            model_name='fieldpostprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_app.program'),
        ),
    ]
