# Generated by Django 3.2 on 2021-06-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_post_app', '0012_auto_20210612_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldpost',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
