# Generated by Django 3.2 on 2021-06-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_post_app', '0013_fieldpost_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpost',
            name='reference_number',
            field=models.CharField(default='FIP/2021/P000', max_length=100, unique=True),
        ),
    ]
