# Generated by Django 3.2 on 2021-06-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_post_app', '0014_alter_fieldpost_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldpost',
            name='applied_chances',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldpost',
            name='reference_number',
            field=models.CharField(default='FIP/2021/F000', max_length=100, unique=True),
        ),
    ]
