# Generated by Django 3.2 on 2021-06-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_post_app', '0015_auto_20210624_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldapplication',
            name='has_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fieldapplication',
            name='has_reported',
            field=models.BooleanField(default=False),
        ),
    ]
