# Generated by Django 3.2 on 2021-04-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='name',
            new_name='designation_name',
        ),
    ]
