# Generated by Django 3.2 on 2021-04-22 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_app', '0002_auto_20210422_1227'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='images/')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_app.department')),
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
