# Generated by Django 3.2 on 2021-04-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0002_rename_name_designation_designation_name'),
        ('staff_profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='designation_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='designation.designation'),
            preserve_default=False,
        ),
    ]
