# Generated by Django 3.2 on 2021-05-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile_app', '0002_staffprofile_designation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='profile_image',
        ),
    ]
