# Generated by Django 3.2 on 2021-06-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile_app', '0003_auto_20210505_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
