# Generated by Django 3.2 on 2021-06-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='cv_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
