# Generated by Django 3.2 on 2021-06-04 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_app', '0003_auto_20210604_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinformation',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_education_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
