# Generated by Django 3.2 on 2021-06-05 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_app', '0004_alter_educationinformation_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_year', models.CharField(max_length=20)),
                ('completion_year', models.CharField(blank=True, max_length=20)),
                ('is_current_job', models.BooleanField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_experience_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
