# Generated by Django 3.2 on 2021-06-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0005_experienceinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienceinformation',
            old_name='completion_year',
            new_name='completion_date',
        ),
        migrations.RenameField(
            model_name='experienceinformation',
            old_name='start_year',
            new_name='start_date',
        ),
    ]
