# Generated by Django 3.2 on 2021-07-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210711_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
