# Generated by Django 3.2 on 2021-07-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
