# Generated by Django 3.2 on 2021-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('number_of_weeks', models.IntegerField(blank=True, null=True)),
                ('last_date_year_of_study_changed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
