# Generated by Django 3.2 on 2021-05-10 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0008_auto_20210506_1443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions_app', '0005_rename_content_multiplechoice_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_post_app.internshippost')),
            ],
        ),
    ]
