# Generated by Django 3.2 on 2021-05-10 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship_post_app', '0008_auto_20210506_1443'),
        ('questions_app', '0006_applicantscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_app.multiplechoice')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_post_app.internshippost')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_app.question')),
            ],
        ),
    ]
