# Generated by Django 3.2 on 2021-04-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_projectmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
    ]
