# Generated by Django 3.2 on 2021-04-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_remove_project_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project_title',
        ),
    ]
