# Generated by Django 3.2 on 2021-05-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0005_rename_project_name_project_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_report',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='member_id',
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sponsor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_member', to='auth.user'),
            preserve_default=False,
        ),
    ]
