# Generated by Django 3.2 on 2021-06-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_auto_20210508_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_created',
            new_name='date_added',
        ),
    ]
