# Generated by Django 3.2 on 2021-07-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_rename_date_created_project_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='recommendation_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
