# Generated by Django 3.2 on 2021-07-05 07:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_alter_project_recommendation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='report',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='project_reports/'),
        ),
    ]
