# Generated by Django 3.2 on 2021-04-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='department',
            new_name='program_department',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='program_name',
        ),
    ]
