# Generated by Django 3.2 on 2021-04-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0002_auto_20210422_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program_department',
            new_name='department_id',
        ),
    ]
