# Generated by Django 3.2 on 2021-08-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0004_rename_department_id_program_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_duration_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
