# Generated by Django 3.2 on 2021-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0002_auto_20210421_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_owner',
            new_name='alumni',
        ),
        migrations.AddField(
            model_name='certificate',
            name='authority',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
