# Generated by Django 3.2 on 2021-06-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0003_auto_20210605_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_name',
            new_name='name',
        ),
    ]
