# Generated by Django 3.2 on 2021-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='closing_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
