# Generated by Django 3.2 on 2021-04-23 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_profile_app', '0003_studentprofile_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
