# Generated by Django 3.2 on 2021-04-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0004_alter_studentprofile_organization_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofession',
            old_name='profession_id',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='studentprofession',
            old_name='student_id',
            new_name='student',
        ),
    ]
