# Generated by Django 3.2 on 2021-04-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0005_auto_20210425_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='program_id',
            new_name='program',
        ),
    ]
