# Generated by Django 3.2 on 2021-04-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0006_rename_program_id_studentprofile_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student_id',
            new_name='student',
        ),
    ]
