# Generated by Django 3.2 on 2021-04-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0007_rename_student_id_studentprofile_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='department_id',
            new_name='department',
        ),
    ]
