# Generated by Django 3.2 on 2021-04-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0009_rename_academic_supervisor_id_studentprofile_academic_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='field_supervisor_id',
            new_name='field_supervisor',
        ),
    ]
