# Generated by Django 3.2 on 2021-04-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0010_rename_field_supervisor_id_studentprofile_field_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
