# Generated by Django 3.2 on 2021-04-26 09:40

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_profile_app', '0011_rename_organization_id_studentprofile_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_owner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
