# Generated by Django 3.2 on 2021-06-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0014_studentprofile_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_reported',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
