# Generated by Django 3.2 on 2021-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0017_auto_20210626_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='average_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='marks_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
