# Generated by Django 3.2 on 2021-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0018_auto_20210626_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cancellation_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
