# Generated by Django 3.2 on 2021-07-05 07:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0019_studentprofile_cancellation_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='field_report',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='field_report/'),
        ),
    ]
