# Generated by Django 3.2 on 2021-07-12 12:42

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0020_alter_studentprofile_field_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='week_1_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='week_2_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='week_3_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='week_4_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='week_5_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='has_reported',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
