# Generated by Django 3.2 on 2021-07-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0021_auto_20210712_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
