# Generated by Django 3.2 on 2021-07-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0022_alter_studentprofile_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='marks_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
