# Generated by Django 3.2 on 2021-08-15 16:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile_app', '0024_alter_studentprofile_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='week_10_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='week_6_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='week_7_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='week_8_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='week_9_logbook',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='logbook/'),
        ),
    ]
