# Generated by Django 3.2 on 2021-04-22 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profession_app', '0001_initial'),
        ('internship_post_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPostProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_profession_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_profession_post_id', to='internship_post_app.internshippost')),
                ('profession_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profession_app.profession')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_application_id', to=settings.AUTH_USER_MODEL)),
                ('internship_application_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_application_post_id', to='internship_post_app.internshippost')),
            ],
        ),
    ]
