# Generated by Django 3.2 on 2021-04-23 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship_post_app', '0002_internshipapplication_internshippostprofession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshippost',
            old_name='post_name',
            new_name='post_titls',
        ),
        migrations.AlterField(
            model_name='internshippost',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
