# Generated by Django 3.2 on 2021-04-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0004_rename_post_titls_internshippost_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshippost',
            old_name='post_name',
            new_name='post_title',
        ),
    ]
