# Generated by Django 3.2 on 2021-04-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0005_rename_post_name_internshippost_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipapplication',
            old_name='alumni_id',
            new_name='alumni',
        ),
        migrations.RenameField(
            model_name='internshipapplication',
            old_name='internship_application_post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='internshippost',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='internshippostprofession',
            old_name='internship_profession_post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='internshippostprofession',
            old_name='profession_id',
            new_name='profession',
        ),
    ]
