# Generated by Django 3.2 on 2021-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0006_auto_20210426_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
