# Generated by Django 3.2 on 2021-05-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession_app', '0001_initial'),
        ('internship_post_app', '0007_internshipapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshippost',
            name='post_title',
        ),
        migrations.AddField(
            model_name='internshippost',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profession_app.profession'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InternshipPostProfession',
        ),
    ]
