# Generated by Django 3.2 on 2021-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0008_auto_20210506_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='test_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(default='received', max_length=100),
        ),
    ]
