# Generated by Django 3.2 on 2021-05-12 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0009_auto_20210513_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
