# Generated by Django 3.2 on 2021-05-17 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship_post_app', '0010_internshipapplication_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='organization',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, related_name='applied_organization', to='auth.user'),
            preserve_default=False,
        ),
    ]
