# Generated by Django 3.2 on 2021-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0011_internshipapplication_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipapplication',
            old_name='test_score',
            new_name='test_marks',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='oral_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='practical_marks',
            field=models.FloatField(null=True),
        ),
    ]
