# Generated by Django 3.2 on 2021-05-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0014_internshipapplicationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
            ],
        ),
    ]
