# Generated by Django 3.2 on 2021-05-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0015_applicantlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='applicant_level',
            field=models.CharField(default='inprogress', max_length=100),
        ),
    ]
