# Generated by Django 3.2 on 2021-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0018_internshippost_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='applicant_level',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='final_stage',
            field=models.CharField(default='inprogress', max_length=100),
        ),
    ]
