# Generated by Django 3.2 on 2021-05-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0020_auto_20210519_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshippost',
            name='expiry_date',
            field=models.CharField(max_length=100),
        ),
    ]
