# Generated by Django 3.2 on 2021-05-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0021_alter_internshippost_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshippost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internshippost',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
