# Generated by Django 3.2 on 2021-05-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0022_auto_20210519_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshippost',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internshippost',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='internshippost',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
