# Generated by Django 3.2 on 2021-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0024_internshipapplication_confirmation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='post_stage',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
