# Generated by Django 3.2 on 2021-05-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0025_interviewschedule_post_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='requirements',
            field=models.CharField(default='', max_length=500),
        ),
    ]
