# Generated by Django 3.2 on 2021-05-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0027_internshipapplication_has_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippost',
            name='reporting_instructions',
            field=models.BooleanField(default=False),
        ),
    ]
