# Generated by Django 3.2 on 2021-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0030_internshipapplication_has_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippost',
            name='minimum_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
