# Generated by Django 3.2 on 2021-07-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_post_app', '0031_internshippost_minimum_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshippost',
            name='post_description',
            field=models.CharField(max_length=3000),
        ),
    ]
