# Generated by Django 3.2 on 2021-04-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='hod',
            new_name='department_hod',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
    ]
