# Generated by Django 3.2 on 2021-04-23 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0002_rename_name_designation_designation_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_supervisor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsupervisorprofile',
            name='designation_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='designation.designation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldsupervisorprofile',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldsupervisorprofile',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
