# Generated by Django 3.2 on 2021-04-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_supervisor_app', '0002_auto_20210423_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldsupervisorprofile',
            old_name='user_id',
            new_name='supervisor_id',
        ),
    ]
