# Generated by Django 3.2 on 2021-05-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_supervisor_app', '0003_rename_user_id_fieldsupervisorprofile_supervisor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldsupervisorprofile',
            name='designation_id',
        ),
        migrations.RemoveField(
            model_name='fieldsupervisorprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='fieldsupervisorprofile',
            name='profile_image',
        ),
    ]
