# Generated by Django 3.2 on 2021-04-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_name',
        ),
    ]
