# Generated by Django 3.2 on 2021-04-22 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profession_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumni_profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profession_id', to=settings.AUTH_USER_MODEL)),
                ('profession_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profession_app.profession')),
            ],
        ),
    ]
