# Generated by Django 3.2 on 2021-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile_app', '0007_rename_is_active_alumniprofile_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
