# Generated by Django 3.2 on 2021-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_profile_app', '0008_alumniprofile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='gpa',
            field=models.FloatField(blank=True, default=2.0),
            preserve_default=False,
        ),
    ]
