# Generated by Django 3.2 on 2021-08-10 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumni_profile_app', '0009_alumniprofile_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='organization',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_organization_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
