# Generated by Django 3.2 on 2021-04-23 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_address_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationaddress',
            name='organization_email',
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='organization_profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='organization_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
