# Generated by Django 3.2 on 2021-07-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_address_app', '0002_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
