# Generated by Django 3.2 on 2021-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_address_app', '0004_auto_20210714_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
