# Generated by Django 3.2 on 2021-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_address_app', '0005_auto_20210714_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationview',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
