# Generated by Django 3.2 on 2021-05-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_address_app', '0006_alter_contract_finish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='alumn',
            new_name='alumni',
        ),
    ]
