# Generated by Django 3.2 on 2021-08-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_address_app', '0006_alter_notificationview_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
