# Generated by Django 3.2 on 2021-06-09 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_address_app', '0012_auto_20210607_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_message', models.CharField(blank=True, max_length=1000)),
                ('rejection_message', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(default='received', max_length=50)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_invited', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviting_organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
