# Generated by Django 3.2 on 2021-06-09 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_address_app', '0013_invitation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invitation',
            new_name='Invitations',
        ),
    ]
