# Generated by Django 3.2 on 2021-06-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_address_app', '0014_rename_invitation_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='has_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitations',
            name='has_reported',
            field=models.BooleanField(default=False),
        ),
    ]
